feat: add searchEngine dropdown into searchinput
Dumbfuckery-Inc/Laudiolin pull request #13
Opened 2023-04-21 09:33 UTC by chiqors

This is my first PR to implement small feature. Let me know if you want to discuss.

Commits
✨ feat: add searchengine dropdown into searchinput component
🚧 wip: it's still using default html selectbox

2023-04-21 09:34 UTC, chiqors commented
This PR for Issue #12

2023-04-23 20:24 UTC, KingRainbow44 requested changes

2023-04-23 20:24 UTC, KingRainbow44 commented on src/ui/components/search/SearchInput.tsx
> +import { SearchEngine } from "@app/backend/types";
correct imports to match existing format (including ordering by import length)

2023-04-23 20:24 UTC, KingRainbow44 commented on src/ui/components/search/SearchInput.tsx
> +        this.state = {
apply spacing

2023-04-23 20:24 UTC, KingRainbow44 commented on src/ui/components/search/SearchInput.tsx
> +                </select>
apply spacing

2023-04-24 01:59 UTC, chiqors commented
would this be enough?

2023-04-24 02:52 UTC, KingRainbow44 requested changes

2023-04-24 02:52 UTC, KingRainbow44 commented on src/ui/components/search/SearchInput.tsx
> +
Remove unnecessary lines.

2023-08-03 05:14 UTC, KingRainbow44 commented
havent gotten around to testing this, will soon i promise lol

2023-08-07 01:57 UTC, KingRainbow44 commented
this was manually merged & updated in `080990ac30135d077de0fd8aa29a24b16a089507`

2023-08-07 01:57 UTC, closed without merging